export const SET_RESPONSABLE = 'SET_RESPONSABLE';
export const SET_SUCCESS_RESPONSABLE = 'SET_SUCCESS_RESPONSABLE';
export const SET_LOADING = 'SET_LOADING';
export const GET_RESPONSABLES = 'GET_RESPONSABLES';
export const SET_RESPONSABLE_LIST = 'SET_RESPONSABLE_LIST';
export const UPDATE_RESPONSABLE = 'UPDATE_RESPONSABLE';
export const SET_SUCCESS_UPDATE_RESPONSABLE = 'SET_SUCCESS_UPDATE_RESPONSABLE';
